# -*- coding: utf-8 -*-
"""brain_age_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E9IoCW5hdafHI57HBy4QiHbFuMsLR1fM
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import ttest_ind, pearsonr

class BrainAgeAnalysis:
    def __init__(self, df, age_col='chronological_age', pred_col='predicted_age', cdr_col='CDR', sex_col='sex'):
        self.df = df.copy()
        self.age_col = age_col
        self.pred_col = pred_col
        self.cdr_col = cdr_col
        self.sex_col = sex_col
        self.df['BAG'] = self.df[self.pred_col] - self.df[self.age_col]
        self.df['CDR_group'] = self.df[self.cdr_col].apply(lambda x: 'Healthy' if x == 0 else 'Impaired')

    def plot_bag_by_cdr(self):
        plt.figure(figsize=(8, 5))
        sns.boxplot(x=self.cdr_col, y='BAG', data=self.df, palette='Set2')
        plt.axhline(0, color='black', linestyle='--')
        plt.title("🧠 Brain Age Gap by CDR Group")
        plt.ylabel("Brain Age Gap (years)")
        plt.xlabel("CDR Score")
        plt.grid(axis='y')
        plt.tight_layout()
        plt.show()

    def plot_bag_distribution_by_cdr_group(self):
        plt.figure(figsize=(8, 5))
        sns.violinplot(x='CDR_group', y='BAG', data=self.df, palette='coolwarm')
        plt.axhline(0, color='black', linestyle='--')
        plt.title("📊 Brain Age Gap Distribution: Healthy vs. Impaired")
        plt.ylabel("Brain Age Gap (years)")
        plt.xlabel("Cognitive Status")
        plt.grid(axis='y')
        plt.tight_layout()
        plt.show()

    def test_bag_difference_by_cdr_group(self):
        healthy_bag = self.df[self.df['CDR_group'] == 'Healthy']['BAG']
        impaired_bag = self.df[self.df['CDR_group'] == 'Impaired']['BAG']
        t_stat, p_val = ttest_ind(healthy_bag, impaired_bag)
        print(f"T-test: t = {t_stat:.3f}, p = {p_val:.4f}")
        return t_stat, p_val

    def plot_bag_vs_age(self):
        plt.figure(figsize=(7, 5))
        sns.scatterplot(x=self.age_col, y='BAG', data=self.df, alpha=0.6)
        sns.regplot(x=self.age_col, y='BAG', data=self.df, scatter=False, color='red')
        plt.axhline(0, color='black', linestyle='--')
        plt.title("📉 BAG vs. Chronological Age")
        plt.xlabel("Chronological Age")
        plt.ylabel("Brain Age Gap")
        plt.grid(True)
        plt.tight_layout()
        plt.show()

    def correlation_bag_with_age(self):
        r, p = pearsonr(self.df[self.age_col], self.df['BAG'])
        print(f"Correlation between age and BAG: r = {r:.3f}, p = {p:.4f}")
        return r, p

    def plot_bag_by_sex(self):
        plt.figure(figsize=(7, 5))
        sns.boxplot(x=self.sex_col, y='BAG', data=self.df, palette='pastel')
        plt.axhline(0, color='black', linestyle='--')
        plt.title("🧬 Brain Age Gap by Sex")
        plt.xlabel("Sex")
        plt.ylabel("Brain Age Gap")
        plt.grid(axis='y')
        plt.tight_layout()
        plt.show()